language: csharp
solution: BeameWindowsInstaller.sln
install:
- nuget restore BeameWindowsInstaller.sln
before_deploy:
- zip -j "beame-windows-installer-${TRAVIS_TAG}.zip" bin/Release/*
deploy:
  provider: releases
  api_key:
    secure: RC8s39mB2KC814iu9/DSKdZWWStPo+3BG+84+ijnBpQCb3BBOyH7gLNJgDJi6KIb/ADUd7Deh5ZOhIKWAnsOXNyCnFxirtH1UQpaARCsc2lJC0PpXte+d2OkEBIDrkmEmO3iY8IVrzKYkASL/A/xxZ1T8aBzEDrRJoxoyYzSp+tlYYBlKYu2oQUulFNwQc9ZsTz6Ga6HtF24ff7dxysRAi9K0jBeot4vkTESUZaUFehj2ih6dzdQ+RJBESBK3k25jpAIGJZgVin7ak8z9XGDBRbMbIQf6CyTaLhnW07RkUvT1/zKuXJPDIVBbGy9IkDBG+n+Ke/d5sJzZ2CJ49KbJ+r23eYPLehIt05NUFXFJ8H3Izhg/BZ2OrsIoKghRxixkbq+N3VoWJmFqTEn0OTmsLcKj5NrfHJI4O3TVrgUBoyWK9sQbWUANzVV/L/1WRHBAlOX0GsBVsPohVF0dNFusOCbqIFeivG3XgezYG+6VBRkyKwm/JfuXKP1RB6AW4jDi/ZO3QhXzRXH2w7Yh+cIo6LlPJD/sDGvsByI3VeGrYiNlKXkINwr1IFED+QzTOkHxS02Pxy3FagRF6HsNM+gDsOcrPoMOKrkoWCseeinD3hcQ9oeZcjyWIVT29ZR/aHiZRoHoH441wFIPj1JL4Mpyw0hc/HQowauGythLPm0loM=
  file: beame-windows-installer-${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    tags: true
